sonar.projectKey=petclinic-frontend
sonar.projectName=PetClinic Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_acbf4bdbd9360527f0232b7c574afccd32a73393

# Configuració específica per a Angular
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts

# Ruta on s'ha guardat l'informe del pas 2
sonar.typescript.lcov.reportPaths=coverage/lcov.info